services:
  # Our PostgreSQL database
  db:
    # The Docker image of postgres == we're using the latest.
    image: postgres:latest
    # The ports to expose to the host container
    # 5432 is the default PostgresSQL port
    ports:
      - "5432:5432"
    # If we accidentally kill the running container, Docker compose will restart it
    restart: always
    # The PostgreSQL Docker container uses environment variables to read
    # configuration, here we set the password.
    # Do not store plaintext passwords in source control

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
